FROM openjdk:11-jre-slim
VOLUME /tmp
VOLUME /log
ARG JAR_FILE
ARG PROJECT
ARG TRAVIS_PROJECT
ARG TRAVIS_BRANCH
ARG TRAVIS_VERSION
LABEL TRAVIS_PROJECT=$TRAVIS_PROJECT
LABEL TRAVIS_BRANCH=$TRAVIS_BRANCH
LABEL TRAVIS_VERSION=$TRAVIS_VERSION

ADD ${JAR_FILE} app.jar
ENV JAVA_OPTS=""
CMD java $JAVA_OPTS \
    -Djava.security.egd=file:/dev/./urandom \
    -Dfile.encoding=UTF8 \
    -Duser.timezone=GMT+08 \
    -jar /app.jar $BOOT_ARGS

EXPOSE 8080
